### ISSUE TITLE
API看起来好不习惯，不能分离出来做一个单独的层次么，，泪目

### ISSUE THREAD

**Issue by jo-wu** [pkwenda/new-bee#28]

**Comment by pkwenda** [comment]
@jo-wu 哦？这位小哥哥能说的具体一点吗，是后端API加个前缀，还是前端router按模块划分呢？

**Comment by jo-wu** [comment]
我想说的是水平分层，独立出一个./api/user.js
把（user）用户相关的ajax调用都抽出来放到里面，
大概是这个意思。

**Comment by pkwenda** [comment]
@jo-wu ok 我明白了，谢谢你提的意见

**Comment by pkwenda** [comment]
@jo-wu 

我整理了 `user`相关目前的前端 `api` [commit](https://github.com/pkwenda/new-bee/commit/a5ce7db8fa6af6feffdb35721f5dbd1f8c9f9c33) 
看起来是这样的
- [user.js](https://github.com/pkwenda/new-bee/blob/master/bbs-vue/src/renderer/api/user.js)

后续的 更多 `api ` 可以都这样处理并修改一下拦截器，比较清晰

公司中午网络不好用的流量😭  再次感谢~   顺便求个 `star`   🤓
