### ISSUE TITLE
Github登录的回调地址可以配置化

### ISSUE THREAD

**Issue by linkerlin** [pkwenda/new-bee#42]
我一般做Github登录，都会配置两个App到Github。
一个 AppX，一个是AppX_Dev。
AppX_Dev的Callback地址写成localhost的。
这样在开发环境也可以登录成功。
因为Github登录是通过浏览器重定向实现的，只要当前的浏览器可以访问本机的localhost上的服务器，即可。
这样会方便很多。
application配置文件也可以搞两个，一个dev一个prod。这样子，就可以方便的切换了。

**Comment by pkwenda** [comment]
@linkerlin 啊哈谢谢，我都是一直改来改去的哈哈
