### ISSUE TITLE
webpack已经不允许 import 和 module.exports 共存

### ISSUE THREAD

**Issue by shanmu2020** [pkwenda/new-bee#49]
![image](https://user-images.githubusercontent.com/28523548/79127057-bc5cef00-7dd3-11ea-9e6c-9d942f2c67e6.png)

**Comment by pkwenda** [comment]
真是抱歉，这个项目已经过时了，不打算维护了，新的基于 vue-cli3 的社区正在建立

https://github.com/gitrue
